name: Build Horadric Helper
on:
  push:
    branches:
      - main
      - ci
jobs:
  Build-Horadric-Helper-Main:
    runs-on: ubuntu-latest
    env:
      working-directory: ./hh-build

    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Check out repository code
        uses: actions/checkout@v2
        working-directory: ${{env.working-directory}}

      - name: Install dependencies
        run: npm ci
        working-directory: ${{env.working-directory}}

      - name: Run tests
        run: npm run test:unit
        working-directory: ${{env.working-directory}}

      - name: Build project
        run: npm run build
        working-directory: ${{env.working-directory}}

      - uses: actions/upload-artifact@v2
        working-directory: ${{env.working-directory}}
        with:
          name: horadric-helper
          path: |
            ./dist/**
            !./dist/**/*.html
            !./dist/**/*.map
