name: Build Horadric Helper
on:
  push:
    branches:
      - main
      - ci
jobs:
  Build-Horadric-Helper-Main:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit

      - name: Build project
        run: npm run build

      - run: ls -la

      - uses: actions/upload-artifact@v2
        with:
          name: horadric-helper
          path: |
            ./dist/**
            !./dist/**/*.html
            !./dist/**/*.map
